name: Publish Theia Builder Docker Image

on:
  push:
    branches:
      - jf/local-theia-build
  workflow_dispatch:
    inputs:
      tag:
        description: The image's tag
        required: true
        default: next

jobs:
  build:
    name: Build and push theia builder image to Github Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/local-theia-build
          file: local-theia-build.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/blueprint-theia-builder:latest
          # ghcr.io/${{ github.repository }}/blueprint-theia-builder:${{ github.event.inputs.tag }}